# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shader',
            name='description',
            field=models.TextField(default='', verbose_name='description'),
        ),
    ]
