# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shaders', '0002_shader_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShaderView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('shader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shaders.Shader', verbose_name='shader')),
            ],
        ),
    ]
