# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaders', '0003_shaderview'),
    ]

    operations = [
        migrations.AddField(
            model_name='shaderview',
            name='session_key',
            field=models.CharField(default='', max_length=40, verbose_name='session key'),
        ),
    ]
